# version: '3.9'

# services:

#   db:
#     image: postgres:15
#     container_name: postgres_db
#     restart: always
#     environment:
#       POSTGRES_DB: hireflow
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 12345
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5432:5432"

#   minio:
#     image: quay.io/minio/minio
#     container_name: minio
#     restart: always
#     command: server /data --console-address ":9001"
#     environment:
#       MINIO_ROOT_USER: admin
#       MINIO_ROOT_PASSWORD: admin123
#     volumes:
#       - minio_data:/data
#     ports:
#       - "9000:9000"
#       - "9001:9001"

#   backend:
#     container_name: django_backend
#     restart: always
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./backend:/app
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#       - minio
#     env_file:
#       - ./backend/.env


# volumes:
#   postgres_data: {}
#   minio_data: {}
version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: hireflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"   
      - "9001:9001"   

volumes:
  postgres_data: {}
  minio_data: {}