version: "3.9"

services:

  # -----------------------------
  # 1️⃣ MAIN DATABASE
  # -----------------------------
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: hireflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # -----------------------------
  # 2️⃣ LIVE CHAT DATABASE
  # -----------------------------
  live_chat_db:
    image: postgres:15
    container_name: live_chat_db
    restart: always
    environment:
      POSTGRES_DB: hireflow_live_db
      POSTGRES_USER: live_chat_user
      POSTGRES_PASSWORD: 12345
    volumes:
      - live_chat_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # -----------------------------
  # 3️⃣ REDIS (Broker + Channels)
  # -----------------------------
  redis:
    image: redis:7-alpine
    container_name: redis_broker
    restart: always
    ports:
      - "6379:6379"

  # -----------------------------
  # 4️⃣ MINIO (Object Storage)
  # -----------------------------
  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  # -----------------------------
  # 5️⃣ MAIN BACKEND (HTTP API)
  # -----------------------------
  backend:
    container_name: django_backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - minio
    env_file:
      - ./backend/.env

  # -----------------------------
  # 6️⃣ LIVE CHAT SERVICE (WebSocket)
  # -----------------------------
  live_chat:
    container_name: django_live_chat
    restart: always
    build:
      context: ./live_services
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./live_services:/app
    ports:
      - "8001:8001"
    depends_on:
      - live_chat_db
      - redis
    env_file:
      - ./live_services/.env

  # -----------------------------
  # 7️⃣ CELERY WORKER (Live Chat)
  # -----------------------------
  celery_worker:
    container_name: live_chat_celery
    restart: always
    build:
      context: ./live_services
      dockerfile: Dockerfile
    command: celery -A live_service_main worker --loglevel=info
    volumes:
      - ./live_services:/app
    depends_on:
      - redis
      - live_chat_db
    env_file:
      - ./live_services/.env

volumes:
  postgres_data:
  live_chat_db_data:
  minio_data: